name: Pull-Request

on:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402

    - name: Setup .NET 2.0.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0.0

    - name: Cake build
      run: ./build.sh
      shell: bash